service: serverless-python

frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  stage: ${opt:stage, "dev"}
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess'

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

functions:
  app:
    package:
      include:
        - "main.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          method: any
          path: /{proxy+}

plugins:
  - serverless-python-requirements
